CXXFLAGS = -O2 -g

exec_file = closet closet_naive stable_match inversions_qsort inversions_merge needleman print_neatly optimal_keypad huffman dijkstra_heap dijkstra_list\
			simplex push_relabel dinic min_cost_flow

all : $(exec_file)

.PHONY : all clean

clean : 
	rm $(exec_file)
